### ISSUE TITLE
File too large to process

### ISSUE THREAD

**Issue by salireza111** [Danialgharaie/DSSP-Pre#1]
Is there any limit on the size of the pdb file to parse?

I got this message with a 2 MB file,
`File too large to process`

**Comment by Danialgharaie** [comment]
Thank you for reporting this issue!

The limitation you're encountering is due to a predefined variable in `include/process_pdb.h` that filters proteins based on the maximum number of lines in the PDB file:

```c
#define MAX_LINES 10000
```

This was added specifically to filter proteins based on the size of the PDB file. However, I might completely remove this limitation in the future to address such issues.

In the meantime, you can change the value of `MAX_LINES` to a much higher number to avoid this error. For example:

```c
#define MAX_LINES 100000
```

After making this change, recompile the code to apply the update. Let me know if you have any further questions or issues!

**Comment by salireza111** [comment]
Great!
